name: Developer Blog of Lukas Martinelli
description: tech, oss, web, js, c#, ideas, python
url: http://lukasmartinelli.ch
markdown: redcarpet
safe: true
pygments: true
exclude: ['CNAME', 'Guardfile', 'README.md']
paginate: 5
prose:
  media: 'media'
  ignore:
    - index.html
    - Gemfile
    - CNAME
    - .gitignore
    - config.rb
    - _config.yml
    - /_layouts
    - /_includes
    - /img
    - /sass
    - /css
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
