name: Lukas Martinelli's Blog
description: I blog about tech, oss, python, web, js, c#, ideas
url: http://lukasmartinelli.ch
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  extensions: ["fenced_code_blocks", "tables"]
safe: true
rouge: true
exclude: ['CNAME', 'Guardfile', 'README.md']
prose:
  media: 'media'
  ignore:
    - index.html
    - Gemfile
    - CNAME
    - .gitignore
    - config.rb
    - _config.yml
    - /_layouts
    - /_includes
    - /img
    - /sass
    - /css
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
